name: Docker

on:
  push:
    tags:
      - "*"

jobs:
  push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - 15.10-alpine
          - 15.10-buster
          - 15.10-buster-slim
          - 15.10-stretch
          - 15.10-stretch-slim
          - lts-alpine

    name: Tag Release (node:${{ matrix.node }})

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: tf2autobot/tf2autobot
          tag-semver: |
            {{version}}-${{ matrix.node }}
            {{major}}.{{minor}}-${{ matrix.node }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (node:${{ matrix.node }})
        id: docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ matrix.node }}
